### ISSUE TITLE
quillEditor.component.ts (14,20): Cannot find namespace 'Quill'.

### ISSUE THREAD

**Issue by lingfengchencn** [surmon-china/ngx-quill-editor#22]
Version "ngx-quill-editor": "^2.1.0",

ERROR in /path/frontend/node_modules/ngx-quill-editor/quillEditor.component.ts (14,20): Cannot find namespace 'Quill'.

ERROR in /path/frontend/node_modules/ngx-quill-editor/quillEditor.component.ts (15,22): Cannot find namespace 'Quill'.

ERROR in /path/frontend/node_modules/ngx-quill-editor/quillEditor.component.ts (16,22): Cannot find namespace 'Quill'.

ERROR in /path/frontend/node_modules/ngx-quill-editor/quillEditor.component.ts (17,18): Cannot find namespace 'Quill'.

ERROR in /path/frontend/node_modules/ngx-quill-editor/quillEditor.component.ts (18,20): Cannot find namespace 'Quill'.

ERROR in /path/frontend/node_modules/ngx-quill-editor/quillEditor.component.ts (19,15): Cannot find name 'require'.
webpack: Failed to compile.

**Comment by damsorian** [comment]
Same error when update to 2.1.0

**Comment by surmon-china** [comment]
This issue is caused by the upgrade, please use the 2.0.2 version, I will solve this problem as soon as possible.

`npm i ngx-quill-editor@2.0.2`

**Comment by kernowjoe** [comment]
Or install the types to be used with the package rather than relying on any type for everything

```npm install --save-dev @types/quill ```
